const GET_EVENT ={
    REQUEST: 'GET_EVENT_REQUEST',
    RECEIVE: 'GET_EVENT_RECEIVE',
    FAILURE: 'GET_EVENT_FAILURE'
}

const GET_EVENT_BY_ID ={
    REQUEST: 'GET_EVENT_BY_ID_REQUEST',
    RECEIVE: 'GET_EVENT_BY_ID_RECEIVE',
    FAILURE: 'GET_EVENT_BY_ID_FAILURE'
}

const GET_CREATOR_BY_ID ={
    REQUEST: 'GET_CREATOR_BY_ID_REQUEST',
    RECEIVE: 'GET_CREATOR_BY_ID_RECEIVE',
    FAILURE: 'GET_CREATOR_BY_ID_FAILURE'
}

export {
    GET_EVENT,
    GET_EVENT_BY_ID,
    GET_CREATOR_BY_ID
}